### PR TITLE
ebmlschema2drupaltable.xsl: initial commit

### PR DESCRIPTION
**Pull request by dericed**
run via `xsltproc ebmlschema2drupaltable.xsl specdata.xml`

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks.

**Comment by dericed** [comment]
Is the output of ```xsltproc ebmlschema2drupaltable.xsl specdata.xml``` semantically similar enough to the existing data2spec output to be sufficient?

**Comment by mbunkus** [comment]
The unified diff looks OK to me. More line breaks, but that's optics, not semantics.

**Comment by mbunkus** [comment]
In fact it looked so good to me that I've just replaced the [official specs page](http://www.matroska.org/technical/specs/index.html) with the output generated by `xsltproc ebmlschema2drupaltable.xsl specdata.xml`.

**Comment by dericed** [comment]
OK from here I can make pull requests on specdata.xml with commits to keep the xsl in sync. But are other xsl necessary? Is this workflow sufficient to support mkvalidator?

data2spec deprecated by the xsl
```
xsltproc ebmlschema2drupaltable.xsl specdata.xml > spec.xml
spec2data
data2lib
data2lib2
```

I am hesitant to rewrite data2lib in xsl as there appears to be a tremendous amount of Matroska login within data2lib.c that is not conveyed within the specdata.xml file.

**Comment by mbunkus** [comment]
I don't think we really need XSL files for creating the library code. We can always fix spec2data if necessary; that should be less work, I guess.

**Pull request merged**
