### PR TITLE
Make usable as dll on windows.

### PR DESCRIPTION
**Pull request by shangjiaxuan**
There are a lot of symbols only declared as extern without export. When compiling as dll, the symbols will not be usable by the linker or LoadLibrary. This along with a tool that adds the export directive in  the generated `matroska_sem.h` header will allow the library to be used as dll on windows. (Such a tool is easily written with regex. May also consider changing the `data2lib2.c` code, but that file is missing form master branch.)

### CODE REVIEW

**Comment by shangjiaxuan** [comment]
Separating EBML and MATROSKA will be more difficult on windows, since the initializers of const structures are dynamically loaded, which means non compile-time constants.

**Comment by robUx4** [comment]
Apparently it's possible to export variables using a.def file instead of dllexport. Since most the useful bits are generated it's possible to generate the .def file as well. I'll give it a try.

https://docs.microsoft.com/en-us/cpp/build/reference/exports?view=msvc-160

**Comment by robUx4** [comment]
It turns out all I was missing in the `dllexport` definition was the `extern` keyword. So it does seem possible to export the EBML context/semantic const variables through a DLL. I'll update the spectools and the CMake project to do this.

**Comment by robUx4** [comment]
Merged #48 which does it without the DLL issue (using getters) and with up to date CMake and core-c.

**Pull request closed without merging**
