### PR TITLE
add doctype v4 to help doc

### PR DESCRIPTION
**Pull request by dericed**

### CODE REVIEW

**Comment by mkver** [comment]
Shouldn't you include a warning that the resulting files will be rejected by most players?

**Comment by dericed** [comment]
@mkver, I can't find a player that rejects Matroska with docType=4. Also it seems that most Matroska files (including those made by ffmpeg) are docType=4.

**Comment by mkver** [comment]
ffmpeg's and MKVToolNix's files are accepted because they also declare a `DocTypeReadVersion` of 2. mkvalidator declares its `DocTypeReadVersion` to be 4 if you use the switch that you want to add to the documentation. And these files are rejected. Here is what ffmpeg says about such files:
```
[matroska,webm @ 0000000000646ec0] EBML version 1, doctype matroska, doc version
 4 is not implemented. Update your FFmpeg version to the newest one from Git. If
 the problem still occurs, it means that your file has a feature which has not b
een implemented.
I:\test.mkv: Not yet implemented in FFmpeg, patches welcome
```
Neither MPC-HC nor vlc open said files. I don't know a player that does.

**Comment by robUx4** [comment]
LGTM value 6 is coded but not mentioned in the inline doc.

**Pull request merged**
