### PR TITLE
create C++-style enums, not C-style

### PR DESCRIPTION
**Pull request by mbunkus**

### CODE REVIEW

**Comment by robUx4** [comment]
Please do not merge code I'm maintaning without giving me a change to agree or disagree. As I said elsewhere, I want to keep this code generator the same between libmatroska and libmatroska2. That implies the enums being typedefs.

**Comment by mbunkus** [comment]
Sorry, I wasn't aware of that. I'll revert both the change here & in libMatroska.

**Comment by mbunkus** [comment]
Reverted directly via ea57e9e50c570e94ee5ba6fb02cec476b72d7f33 without a PR. same for libMatroska.

**Comment by robUx4** [comment]
Technically I would like to make a single file for both libraries (on generator). I quikly added it to `KaxSemantic.h` because it was the fastest option.

**Comment by robUx4** [comment]
It's not blocking the release though. It can be added later and included from `KaxSemantic.h` for backward compatibility.

**Pull request merged**
