### PR TITLE
Add colour for video track entry

### PR DESCRIPTION
**Pull request by chenchao1983**
Dear Colleagues,
Please have a look at this patch.
This patch is to enable the "Colour" element under Track->TrackEntry->Video element. Using this element, we can provide metadata about video colour space using matroska. This will help YouTube to use Matroska for muxing HDR/wide-colour-gamut videos.

The Colour element is proposed by Google Inc. to IETF. Please check this email [thread](https://mailarchive.ietf.org/arch/search/?email_list=cellar) for more information.

best regards,
Chao Chen (chaochen@google.com)

### CODE REVIEW

**Comment by mbunkus** [comment]
Thanks. I'll leave some wishes as line comments.

**Comment by mbunkus** [comment]
LGTM. Thanks.

**Comment by chenchao1983** [comment]
Thank you very much. I am wondering when will you update libmatroska? We are planning to add support for the colour attributes to mkvtoolnix. It would be nice if we could use the updated libmatroska library.

best regards,
Chao Chen

**Comment by mbunkus** [comment]
Please note that you forgot to add `minver` and `webm` attributes. Especially the `minver` is rather important. If it's missing then this means that the element has been deprecated.

I've added both attributes in e5b66250a84f7d725e31613847a375b22e5c9672.

I've also updated libmatroska and libmatroska2 with the new elements.

**Comment by chenchao1983** [comment]
Thank you very much for correcting my code and updating the library. Please let me know if any bug is reported to these elements.

**Pull request merged**
